[[setting-up]]
= Setting up a reactive Hibernate project

:skeleton: https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=r1s.8XW.fmW.ih0&cn=code.quarkus.io

If you're using Hibernate Reactive outside of the Quarkus environment,
you'll need to:

- include Hibernate Reactive itself, along with the appropriate Vert.x
  reactive database client, as dependencies of your project, and
- configure Hibernate Reactive with information about your database,
  using Hibernate configuration properties.

Or, if you want to use Hibernate Reactive in Quarkus, you can generate
a preconfigured skeleton project {skeleton}[right here].

== Including Hibernate Reactive in your project build

:build: https://github.com/hibernate/hibernate-reactive/blob/main/examples/session-example/build.gradle

Add the following dependency to your project:

----
org.hibernate.reactive:hibernate-reactive-core:{version}
----

Where `{version}` is the version of Hibernate Reactive you're using.

You'll also need to add a dependency for the Vert.x reactive database
driver for your database, one of the following options:

|===
| Database                  | Driver dependency

| PostgreSQL or CockroachDB | `io.vertx:vertx-pg-client:{vertxSqlClientVersion}`
| MySQL or MariaDB          | `io.vertx:vertx-mysql-client:{vertxSqlClientVersion}`
| DB2                       | `io.vertx:vertx-db2-client:{vertxSqlClientVersion}`
| SQL Server                | `io.vertx:vertx-mssql-client:${vertxSqlClientVersion}`
| Oracle                    | `io.vertx:vertx-oracle-client:${vertxSqlClientVersion}`
|===

Where `{vertxSqlClientVersion}` is the version of Vert.x compatible with the
version of Hibernate Reactive you're using.

You don't need to depend on the JDBC driver for your database.

== Optional dependencies

:slf4j: http://www.slf4j.org/
:enhancer: https://docs.hibernate.org/orm/{ormMinorVersion}/topical/html_single/bytecode/

Optionally, you might also add any of the following additional features:

|===
| Optional feature | Dependencies

| An {slf4j}[SLF4J] logging implementation | `org.apache.logging.log4j:log4j-core` or `org.slf4j:slf4j-jdk14`
| The Hibernate metamodel generator, if you're using the JPA criteria query API | `org.hibernate.orm:hibernate-jpamodelgen`
| Hibernate Validator | `org.hibernate.validator:hibernate-validator` and `org.glassfish:jakarta.el`
| Compile-time checking for your HQL queries | `org.hibernate:query-validator`
| Second-level cache support via JCache and EHCache | `org.hibernate.orm:hibernate-jcache` along with `org.ehcache:ehcache`
| SCRAM authentication support for PostgreSQL | `{scramArtifact}`
|===

You might also add the Hibernate {enhancer}[bytecode enhancer] to your
Gradle build if you want to use field-level  lazy fetching.

TIP: Field-level lazy fetching is an advanced feature that most programs
don't need. Stick to the basics for now.

There's an example {build}[Gradle build] included in the example program.

== Basic configuration

:xml: https://github.com/hibernate/hibernate-reactive/blob/main/examples/session-example/src/main/resources/META-INF/persistence.xml
:configuration-properties: https://docs.hibernate.org/orm/{ormMinorVersion}/userguide/html_single/#configurations


Hibernate Reactive is configured via the standard JPA `persistence.xml`
document which must be placed, as usual, in the `/META-INF` directory.

An example {xml}[`persistence.xml`] file is included in the example
program.

The only required configuration that's really specific to Hibernate
Reactive is the persistence `<provider>` element, which must be explicit:

[source,xml]
----
<provider>org.hibernate.reactive.provider.ReactivePersistenceProvider</provider>
----

Otherwise, configuration is almost completely transparent&mdash;you can
configure Hibernate Reactive pretty much exactly as you would usually
configure Hibernate ORM core.

Just like in regular JPA, you should list your entity classes in `persistence.xml`:

[source,xml]
----
<class>org.hibernate.reactive.example.session.Author</class>
<class>org.hibernate.reactive.example.session.Book</class>
----

A full list of configuration properties recognized by Hibernate may be
found in the {configuration-properties}[documentation for Hibernate ORM].
You'll never need to touch most of these. The properties you do need at
this stage are these three:

|===
| Configuration property name                                         | Purpose

| `jakarta.persistence.jdbc.url`                                        | JDBC URL of your database
| `jakarta.persistence.jdbc.user` and `jakarta.persistence.jdbc.password` | Your database credentials
|===

These configuration properties have `jdbc` in their names, but of course
there's no JDBC in Hibernate Reactive, and these are simply the legacy
property names defined by the JPA specification. In particular, Hibernate
Reactive itself parses and interprets the JDBC URL.

TIP: You don't need to specify `hibernate.dialect`. The correct Hibernate
`Dialect` will be determined for you by Hibernate Reactive.

The Vert.x database client has built-in connection pooling and prepared
statement caching. You might want to control the size of the connection
pool:

|===
| Configuration property name      | Purpose

| `hibernate.connection.pool_size` | The maximum size of the reactive connection pool
|===

We'll learn about more advanced connection pool tuning later, in
<<_tuning_the_vert_x_pool>>.

TIP: Hibernate has many configurable things, but many exist only to
maintain compatibility with legacy code, and most configuration properties
directly related to JDBC or JTA aren't relevant in the context of Hibernate
Reactive.

== Automatic schema export

You can have Hibernate Reactive infer your database schema from the mapping
annotation you've specified in your Java code, and export the schema at
initialization time by specifying one or more of the following configuration
properties:

[cols="1,1"]
|===
| Configuration property name                                | Purpose

| `jakarta.persistence.schema-generation.database.action` 
a| * If `create`, first drop the schema and then export tables, sequences, and constraints.
   * If `create-only`, export tables, sequences, and constraints.
   * If `create-drop`, drop the schema and recreate it on SessionFactory startup.
     Additionally, drop the schema on SessionFactory shutdown.
   * If `drop`, drop the schema on SessionFactory shutdown.
   * If `validate`, validate the database schema without changing it.
   * If `update`, only export what's missing in the schema.

| `jakarta.persistence.create-database-schemas`
| (Optional) If `true`, automatically create schemas and catalogs

| `jakarta.persistence.schema-generation.create-source`
| (Optional) If `metadata-then-script` or `script-then-metadata`, execute an additional SQL script when exported tables and sequences

| `jakarta.persistence.schema-generation.create-script-source`
| (Optional) The name of the SQL script to be executed
|===

This feature is extremely useful for testing.

IMPORTANT: Hibernate Reactive doesn't support `validate` and `update` with Db2.

Schema export uses blocking operations so starting the factory might require special
handling when using it. Failing to do so will cause an exception:

[source,java]
----
io.vertx.core.VertxException: Thread blocked
----

You can solve this issue using `executeBlocking`:

[source,java]
----
Vertx vertx = ...

Uni<Void> startHibernate = Uni.createFrom().deferred(() -> {
  emf = Persistence
    .createEntityManagerFactory("demo")
    .unwrap(Mutiny.SessionFactory.class);

  return Uni.createFrom().voidItem();
});

startHibernate = vertx.executeBlocking(startHibernate)
  .onItem().invoke(() -> logger.info("✅ Hibernate Reactive is ready"));
----

== Logging the generated SQL

:log4j: https://github.com/hibernate/hibernate-reactive/blob/main/examples/session-example/src/main/resources/log4j2.properties

To see the generated SQL as it's sent to the database, either:

- set the property `hibernate.show_sql` to `true`, or
- enable debug-level logging for the category `org.hibernate.SQL`
  using your preferred SLF4J logging implementation.

For example, if you're using Log4J 2 (as above in <<_optional_dependencies>>),
add these lines to your `log4j2.properties` file:

[source,properties]
----
logger.hibernate.name = org.hibernate.SQL
logger.hibernate.level = debug
----

An example {log4j}[`log4j2.properties`] file is included in the example
program.

You can make the logged SQL more readable by enabling one or both of
the following settings:

|===
| Configuration property name | Purpose

| `hibernate.format_sql`      | If `true`, log SQL in a multiline, indented format
| `hibernate.highlight_sql`   | If `true`, log SQL with syntax highlighting via ANSI escape codes
|===

== Minimizing repetitive mapping information

The following properties are very useful for minimizing the amount of
information you'll need to explicitly specify in `@Table` and `@Column`
annotations which we'll discuss below in <<_mapping_entity_classes>>:

|===
| Configuration property name           | Purpose

| `hibernate.default_schema`            | A default schema name for entities which do not explicitly declare one
| `hibernate.default_catalog`           | A default catalog name for entities which do not explicitly declare one
| `hibernate.physical_naming_strategy`  | A `PhysicalNamingStrategy` implementing your database naming standards
|===

TIP: Writing your own `PhysicalNamingStrategy` is an especially good
way to reduce the clutter of annotations on your entity classes, and
we think you should do it for any nontrivial data model.

== Nationalized character data in SQL Server

_By default,_ SQL Server's `char` and `varchar` types don't accommodate
Unicode data. So, if you're working with SQL Server, you might need to
force Hibernate to use the `nchar` and `nvarchar` types.

|===
| Configuration property name                 | Purpose

| `hibernate.use_nationalized_character_data` | Use `nchar` and `nvarchar` instead of `char` and `varchar`
|===

TIP: Alternatively, you can configure SQL Server to use the UTF-8 enabled
collation `_UTF8`.

