[[getting-started]]
= Introduction to Hibernate Reactive

:example: https://github.com/hibernate/hibernate-reactive/tree/master/example

Creating a new project with Hibernate Reactive isn't hard at all. In this
short guide, we'll cover all the basic work involved in:

- setting up and configuring a project, and then
- writing Java code to define a data model and access the database.

But, before you start, we recommend taking a quick look at the example
program in the {example}[`example`] directory, which shows off all the
"bits" you'll need to get your own program up and running.

== Setting up a reactive Hibernate project

:skeleton: https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=r1s.8XW.fmW.ih0&cn=code.quarkus.io

If you're using Hibernate Reactive outside of the Quarkus environment,
you'll need to:

- include Hibernate Reactive itself along with the appropriate Vert.x
  reactive database client as dependencies of your project, and
- configure Hibernate Reactive with information about your database,
  using Hibernate configuration properties.

Or, if you want to use Hibernate Reactive in Quarkus, you can generate
a preconfigured skeleton project {skeleton}[right here].

=== Including Hibernate Reactive in your project build

:build: https://github.com/hibernate/hibernate-reactive/blob/master/example/build.gradle

Add the following dependency to your project:

----
org.hibernate.reactive:hibernate-reactive-core:{version}
----

Where `{version}` is the version of Hibernate Reactive you're using.

You'll also need to add a dependency for the Vert.x reactive database
driver for your database, for example:

- `io.vertx:vertx-pg-client` for Postgres,
- `io.vertx:vertx-mysql-client` for MySQL, or
- `io.vertx:vertx-db2-client` for DB2.

You don't need to depend on the JDBC driver for your database (but you
can if you like).

=== Optional dependencies

:slf4j: http://www.slf4j.org/
:enhancer: https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html

Optionally, you might also add:

- an {slf4j}[SLF4J] logging implementation, for example,
  `org.slf4j:slf4j-log4j12`,
- `org.hibernate:hibernate-jpamodelgen` if you're using the JPA criteria
  query API,
- `org.hibernate.validator:hibernate-validator` and
  `org.glassfish:jakarta.el` if you're using Hibernate Validator,
- `org.hibernate:query-validator` to enable compile-time checking of your
  HQL queries, and/or
- the Hibernate {enhancer}[bytecode enhancer] if you want to use field-level
  lazy fetching.

TIP: Field-level lazy fetching is an advanced feature that most programs
don't need. Stick to the basics for now.

There's an example {build}[Gradle build] included in the example program.

=== Configuration

:xml: https://github.com/hibernate/hibernate-reactive/blob/master/example/src/main/resources/META-INF/persistence.xml

Hibernate Reactive is configured via the standard JPA `persistence.xml`
document which must be placed, as usual, in the `/META-INF` directory.

The only configuration specific to Hibernate Reactive is the persistence
`<provider>` element, which must be explicit:

[source,xml]
----
<provider>org.hibernate.reactive.provider.ReactivePersistenceProvider</provider>
----

Otherwise, configuration is almost completely transparent. Configure
Hibernate exactly as you usually would, noting that most configuration
properties related to JDBC or JTA aren't relevant in the context of
Hibernate Reactive.

Configuration properties of particular interest include:

- `javax.persistence.jdbc.url`, the JDBC URL of your database,
- `javax.persistence.jdbc.user` and `javax.persistence.jdbc.password`,
the database credentials,
- `javax.persistence.schema-generation.database.action`, for enabling
  automatic schema export.

An example {xml}[`persistence.xml`] file is included in the example
program.

=== Logging the generated SQL

:log4j: https://github.com/hibernate/hibernate-reactive/blob/master/example/src/main/resources/log4j.properties

To see the generated SQL as it's sent to the database, either:

- set the property `hibernate.show_sql` to `true`, or
- enable debug-level logging for the category `org.hibernate.SQL`
  using your preferred SLF4J logging implementation.

For example, if you're using Log4J via `slf4j-log4j12` (as above in
<<_optional_dependencies>>), add this line to your `log4j.properties`
file:

[source,properties]
----
log4j.logger.org.hibernate.SQL=DEBUG
----

An example {log4j}[`log4j.properties`] file is included in the example
program.

=== Tuning the Vert.x pool

The Vert.x database client has built-in connection pooling and prepared
statement caching.

- Use `hibernate.connection.pool_size` to set the size of the reactive
  connection pool.

When it comes time for performance tuning, you can further customize the
pool and cache via the following properties:

- `hibernate.vertx.pool.max_wait_queue_size`
- `hibernate.vertx.prepared_statement_cache.max_size`
- `hibernate.vertx.prepared_statement_cache.sql_limit`

TIP: But for now, just leave these three settings alone.

== Writing the Java code

With that out of the way, we're all set to write some Java code!

As is the case in any project that uses Hibernate, your
persistence-related code comes in two main pieces:

. a representation of your data model in Java, which takes the form
  of a set of annotated entity classes, and
. a larger number of functions which interact with Hibernate's APIs
  to perform the persistence operations associated with your various
  transactions.

The first part, the data or "domain" model, is usually easier to write,
but doing a great and very clean job of it will strongly affect your
success in the second part.

TIP: Take your time with this code, and try to produce a Java model
that's as close as reasonable to the relational data model. Avoid using
exotic or advanced mapping features when they're not really needed.
When in the slightest doubt, map a foreign key relationship using
`@ManyToOne` with `@OneToMany(mappedBy=...)` in preference to more
complicated association mappings.

The second part of the code is much trickier to get right. This code must:

- manage transactions and reactive sessions,
- construct reactive streams by chaining persistence operations invoked
  on the reactive session,
- fetch and prepare data needed by the UI, and
- handle failures.

TIP: Some responsibility for transaction and session management, and for
recovery from certain kinds of failure, can be best handled in some sort
of framework code.

=== Mapping entity classes

We won't have much to say about the entity classes here, simply because
the principles behind mapping entity classes in Hibernate Reactive,
along with the actual mapping annotations you'll use, are all identical
to regular Hibernate ORM and other implementations of JPA.

For example:

[source,java]
----
@Entity
@Table(name="authors")
class Author {
    @Id @GeneratedValue
    Integer id;

    @NotNull @Size(max=100)
    String name;

    @OneToMany(mappedBy = "author", cascade = PERSIST)
    List<Book> books = new ArrayList<>();

    Author(String name) {
        this.name = name;
    }

    Author() {}
}
----

You're quite free to mix and match:

- the regular JPA mapping annotations defined in the package
  `javax.persistence` with
- the advanced mapping annotations in `org.hibernate.annotations`.

Most mapping annotations are already supported in Hibernate Reactive,
though there are still a handful of limitations at this time.

=== Identifier generation

One area where the functionality of Hibernate Reactive diverges from plain
Hibernate is in the area of id generation. Custom identifier generators
written to work with Hibernate ORM and JDBC will _not_ work in the reactive
environment.

- Sequence, table, and `UUID` id generation is built in, and these id
  generation strategies may be selected using the usual JPA mapping
  annotations: `@GeneratedValue`, `@TableGenerator`, `@SequenceGenerator`.
- Natural ids&mdash;including composite ids&mdash;may be assigned by the
  program in the usual way.
- Custom id generators may be defined by implementing `ReactiveIdentifierGenerator`
  and declaring the custom implementation using `@GenericGenerator`.

=== Custom types

Hibernate custom types based on the `UserType` interface are similarly
targeted toward JDBC. Hibernate Reactive features an adaptor that exposes a
partial implementation of JDBC to the `UserType` implementation.

Therefore, _some_ existing `UserType` implementations will work in Hibernate
Reactive, depending upon precisely which features of JDBC they depend on.

TIP: Where possible, use a JPA `AttributeConverter` instead of a `UserType`,
since JPA converters are not in any way tied to JDBC.

=== APIs for chaining reactive operations

:Mutiny: https://smallrye.io/smallrye-mutiny/

When you write persistence logic using Hibernate Reactive, you'll be working
with a reactive `Session` most of the time. Just to make things a little more
confusing for new users, the reactive `Session` and its related interfaces all
come in two flavors:

- `Stage.Session` and friends provide a reactive API based around Java's
`CompletionStage`, and
- `Mutiny.Session` and friends provide an API based on {Mutiny}[Mutiny].

You'll need to decide which API you want to use!

TIP: If you take the time to look over the types `Stage.Session` and
`Mutiny.Session`, you'll notice they're almost identical. Choosing between
them is a matter of deciding which reactive API you want to use for working
with reactive streams. Your decision won't affect what you can do with
Hibernate Reactive.

In this introduction, our code examples usually use `CompletionStage`, since
that's what more people are already familiar with. But please don't take that
as a recommendation.

When we use the term _reactive stream_ in this document, we mean:

- a chain of ``CompletionStage``s, or
- a chain of Mutiny ``Uni``s and ``Multi``s

that is built by the program in order to service a particular request,
transaction, or unit of work.

=== Obtaining a reactive session factory

Whatever you decide, the first step to getting a reactive session is to obtain
a JPA `EntityManagerFactory` just as you usually would in plain ol' regular JPA,
for example, by calling:

[java]
----
EntityManagerFactory emf = Persistence.createEntityManagerFactory("example");
----

Now, `unwrap()` the reactive `SessionFactory`. If you want to use
``CompletionStage``s for chaining reactive operations, ask for a
`Stage.SessionFactory`:

[java]
----
Stage.SessionFactory sessionFactory = emf.unwrap(Stage.SessionFactory.class);
----

Or, if you prefer to use the Mutiny-based API, `unwrap()` the type
`Mutiny.SessionFactory`:

[java]
----
Mutiny.SessionFactory sessionFactory = emf.unwrap(Mutiny.SessionFactory.class);
----

Reactive sessions may be obtained from the resulting reactive `SessionFactory`.

TIP: It's also possible to construct a reactive `SessionFactory` via programmatic
configuration based on Hibernate's `ServiceRegistry` architecture, by using a
`ReactiveServiceRegistryBuilder`. But that's outside the scope of this document.

=== Obtaining a reactive session

Persistence operations are exposed via a reactive `Session` object. It's very
important to understand that most operations of this interface are non-blocking,
and execution of SQL against the database is never performed synchronously.
Persistence operations that belong to a single unit of work must be chained by
composition within a single reactive stream.

Also remember that a Hibernate session is a lightweight object that should be
created, used, and then discarded within a single logical unit of work.

TIP: That is to say, you should reuse the same session across multiple
persistence operations within a single reactive stream representing a certain
unit of work, but don't share a session between different reactive streams!

To obtain a reactive `Session` from the `SessionFactory`, use `withSession()`:

[java]
----
sessionFactory.withSession(
        session -> ... //do some work
);
----

Alternatively, you may use `openSession()`, but you must remember to `close()`
the session when you're done.

[java]
----
sessionFactory.openSession()
        .thenCompose(
            session -> ... //do some work
                    .whenComplete( ($,e) -> session.close() )
        );
----

=== Using the reactive session

The `Session` interface has methods with the same names as methods of the
JPA `EntityManager`. You might already be familiar with the following session
operations defined by JPA:

- `find()` obtains a persistent object given its id (its primary key),
- `persist()` makes a transient object persistent and schedules a SQL
  insert statement,
- `remove()` makes a persistent object transient and schedules a SQL
  delete statement,
- `merge()` copies the state of a transient object to a corresponding
   persistent instance and returns the persistent object,
- `refresh()` refreshes the persistent state of an object,
- `lock()` obtains a pessimistic lock on a persistent object,
- `flush()` synchronizes the database state with the current session by
   executing SQL insert, update, and delete statements, and
- `detach()` detaches a persistent object from a session without affecting
   the database.

If you're not familiar with these operations, don't despair! Their semantics
are defined in the JPA specification, and in the API documentation, and are
explained in innumerable articles and blog posts.

Now, _here's where Hibernate Reactive is different:_ in the reactive API, each
of these methods returns its result in a non-blocking fashion via a Java
`CompletionStage` (or Mutiny `Uni`). For example:

[java]
----
session1.find(Book.class, book.id)
        .thenAccept( book -> System.out.println(book.title + " is a great book!") )
----

On the other hand, methods with no meaningful return value just return a
reference to the `Session`, allowing chaining with `thenCompose()`:

[java]
----
sessionFactory.openSession()
        .thenCompose( session -> session.flush() )
        .whenComplete( (session,e) -> session.close() )
----

TIP: The session will be flushed automatically at the end of a unit of work
if&mdash;and _only_ if&mdash;you use a transaction, as described below in
<<_transactions>>. If you don't use a transaction, and forget to flush the
session explicitly, your persistence operations might never be sent to the
database!

If you already know Hibernate, and if you already have some experience with
reactive programming, there's not much new to learn here: you should
immediately feel right at home.

=== Queries

Naturally, the `Session` interface is a factory for `Query` instances which
allow you to set query parameters and execute queries and DML statements:

- `createQuery()` lets you run HQL and JPQL queries and DML statements,
- `createNativeQuery()` lets you run native SQL queries and DML statements,
  and
- `createNamedQuery()` lets you run a named HQL or SQL query.

That `createQuery()` method produces a reactive `Query`, allowing HQL / JPQL
queries to be executed asynchronously, always returning their results via a
`CompletionStage` (or `Uni`):

[java]
----
session3.createQuery("select title from Book order by title desc")
        .getResultList()
        .thenAccept(System.out::println)
----

TIP: The Hibernate Reactive `Query` API doesn't support `java.util.Date`
or its subclasses in `java.sql`, nor `java.util.Calendar`. Always use
`java.time` types for binding temporally-typed query parameters.

For  JPA criteria queries, you must first obtain the `CriteriaBuilder` using
`SessionFactory.getCriteriaBuilder()`, and execute your query using
`Session.createQuery()`.

[java]
----
CriteriaQuery<Book> query = factory.getCriteriaBuilder().createQuery(Book.class);
Root<Author> a = query.from(Author.class);
Join<Author,Book> b = a.join(Author_.books);
query.where( a.get(Author_.name).in("Neal Stephenson", "William Gibson") );
query.select(b);
return session.createQuery(query).getResultList().thenAccept(
        books -> books.forEach(book -> out.println(book.title))
);
----

=== Fetching lazy associations

In Hibernate ORM, a lazy association is fetched transparently when the
association is first accessed within a session. In Hibernate Reactive, on
the other hand, lazy association fetching is an asynchronous process that
produces a result via a `CompletionStage` (or `Uni`).

Therefore, lazy fetching is an explicit operation named `fetch()`, a static
method of `Stage` and `Mutiny`:

[java]
----
session4.find(Author.class, author.id)
        .thenCompose( author -> Stage.fetch(author.books) )
        .thenAccept( books -> ... )
----

Of course, this isn't necessary if you fetch the association eagerly.

TIP: It's very important to make sure you've fetched all the data that
will be needed before passing control to the process that renders the
UI! There is no transparent lazy fetching in Hibernate Reactive, so
patterns like "open session in view" will _not help at all_.

=== Field-level lazy fetching

Similarly, field-level lazy fetching&mdash;an advanced feature, which
is only supported in conjunction with Hibernate's optional compile-time
bytecode enhancer&mdash;is also an explicit operation:

[java]
----
session5.find(Book.class, book.id)
        .thenCompose( book -> session.fetch(book, Book_.isbn) )
        .thenAccept( isbn -> ... )
----

Note that the field to fetch is identified by a JPA metamodel `Attribute`.

TIP: We don't encourage you to use field-level lazy fetching unless you
have very specific requirements.

=== A reminder about performance

As always, achieving high performance in ORM means minimizing the number
of round trips to the database. This goal should be uppermost in your
mind whenever you're writing data access code with Hibernate. The most
fundamental rule of thumb in ORM is:

- explicitly specify all the data you're going to need right at the start
of a session/transaction, and fetch it immediately in one or two queries,
- and only then start navigating associations between persistent entities.

TIP: Don't forget that most associations should be mapped for lazy
fetching by default. If you need eager fetching in some particular
transaction, use `left join fetch` in HQL, a fetch profile, a JPA
`EntityGraph`, or `fetch()` in a criteria query.

It follows from this tip that you shouldn't need to use `Stage.fetch()`
or `Mutiny.fetch()` very often!

=== Transactions

The `withTransaction()` method performs work within the scope of a database
transaction.

[java]
----
session.withTransaction( tx -> session.persist(book) )
----

The session is automatically flushed at the end of the transaction.

For extra convenience, there's a method that opens a session and starts a
transaction in one call:

[java]
----
sessionFactory.withTransaction( (session, tx) -> session.persist(book) )
----

Note that these are "resource local" transactions, delegated to the underlying
Vert.x database client.

== Next steps

:Quarkus: https://quarkus.io/
:Panache: https://quarkus.io/guides/hibernate-orm-panache

Hibernate Reactive is now integrated in {Quarkus}[Quarkus] and {Panache}[Panache].
Configuration works slightly differently in Quarkus, so be sure to check the Quarkus
documentation for details.