package org.hibernate.rx.service;

import org.hibernate.rx.service.initiator.RxConnectionPoolProvider;
import org.hibernate.service.ServiceRegistry;
import org.hibernate.tool.schema.internal.exec.GenerationTarget;

/**
 * Adaptor that redirects DDL generated by the schema export
 * tool to the reactive connection.
 *
 * @author Gavin King
 */
public class RxGenerationTarget implements GenerationTarget {
	RxConnection connection;
	private ServiceRegistry registry;

	public RxGenerationTarget(ServiceRegistry registry) {
		this.registry = registry;
	}

	@Override
	public void prepare() {
		connection = registry.getService( RxConnectionPoolProvider.class ).getConnection();
	}

	@Override
	public void accept(String command) {
		try {
			connection.preparedQuery(command).toCompletableFuture().join();
		}
		catch (Exception e) {
			System.out.println( e.getMessage() );
		}
	}

	@Override
	public void release() {
		connection.close();
		connection = null;
	}
}
